version: "3"

services:

  # Nginx Service
  nginx:
    image: "nginx:stable-alpine"
    ports:
    - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    networks:
      - app-network

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - db
    container_name: php
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge